// Copyright (C) 1991-2014 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus II License Agreement,
// the Altera MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Altera and sold by Altera or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus II 64-Bit Version 14.1 (Build Build 186 12/03/2014)
// Created on Mon Jan 11 17:39:55 2016

count_down_schematic count_down_schematic_inst
(
	.CLOCK(CLOCK_sig) ,	// input  CLOCK_sig
	.RESET(RESET_sig) ,	// input  RESET_sig
	.out(out_sig) ,	// output [0]:ut[0]] out_sig
	.out(out_sig) ,	// output [1]:ut[1]] out_sig
	.out(out_sig) ,	// output [2]:ut[2]] out_sig
	.out(out_sig) 	// output [3]:ut[3]] out_sig
);

